//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWJ.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QinuoOAEntities : DbContext
    {
        public QinuoOAEntities()
            : base("name=QinuoOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<InvoiceAttachments> InvoiceAttachments { get; set; }
        public virtual DbSet<Money> Money { get; set; }
        public virtual DbSet<node> node { get; set; }
        public virtual DbSet<OfferTable> OfferTable { get; set; }
        public virtual DbSet<Paymentapplicationform> Paymentapplicationform { get; set; }
        public virtual DbSet<paymentnode> paymentnode { get; set; }
        public virtual DbSet<Platform> Platform { get; set; }
        public virtual DbSet<PO> PO { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<projectCostlujing> projectCostlujing { get; set; }
        public virtual DbSet<ProjectFinalReport> ProjectFinalReport { get; set; }
        public virtual DbSet<ProjectQuotationlujing> ProjectQuotationlujing { get; set; }
        public virtual DbSet<ProjecTtype> ProjecTtype { get; set; }
        public virtual DbSet<Publishlinksummary> Publishlinksummary { get; set; }
        public virtual DbSet<role_permission> role_permission { get; set; }
        public virtual DbSet<t_permission> t_permission { get; set; }
        public virtual DbSet<t_role> t_role { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
