//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Money
    {
        public int Id { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<decimal> NoTaxlMoney { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<decimal> projectcost { get; set; }
        public Nullable<decimal> CostQuotation { get; set; }
        public Nullable<decimal> SalesQuotation { get; set; }
        public Nullable<decimal> Actualamountofpayment { get; set; }
        public Nullable<decimal> Financialcost { get; set; }
        public Nullable<decimal> Totaltaxcost { get; set; }
        public Nullable<decimal> SalesQuotations { get; set; }
        public Nullable<decimal> TaxSum { get; set; }
        public Nullable<decimal> NonTaxCostCombined { get; set; }
        public Nullable<decimal> Totaltaxcosttow { get; set; }
        public Nullable<decimal> Grossprofit { get; set; }
        public Nullable<decimal> Unpaidchannel { get; set; }
        public Nullable<decimal> Employeebonus { get; set; }
        public Nullable<decimal> Undistributedprofit { get; set; }
        public string Percentageofprofit { get; set; }
        public string AMargemBrutapercentual { get; set; }
        public Nullable<decimal> Olucrolíquido { get; set; }
        public string Aporcentagemdelucrolíquido { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
