//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        public int Id { get; set; }
        public Nullable<int> Stateofapproval { get; set; }
        public Nullable<int> projectid { get; set; }
        public string AE { get; set; }
        public string SAE { get; set; }
        public string AD { get; set; }
        public string SAD { get; set; }
        public string yinxiaozongjian { get; set; }
        public string caiwu { get; set; }
        public string laoban { get; set; }
        public string zhulaoban { get; set; }
        public Nullable<int> processstate { get; set; }
    }
}
