//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paymentapplicationform
    {
        public int Id { get; set; }
        public Nullable<int> Invoicenumber { get; set; }
        public Nullable<decimal> Invoicetax { get; set; }
        public Nullable<System.DateTime> Timeofpayment { get; set; }
        public string Receivablescompany { get; set; }
        public string Openingbank { get; set; }
        public string Bankaccount { get; set; }
        public string Remarks { get; set; }
        public int ProjectId { get; set; }
        public string Payee { get; set; }
        public string ApplyforpaymentType { get; set; }
        public string Paymentobject { get; set; }
        public Nullable<int> xuhao { get; set; }
        public Nullable<int> MoneyId { get; set; }
        public Nullable<decimal> CostQuotation { get; set; }
        public Nullable<decimal> Salesquotation { get; set; }
        public Nullable<decimal> Actualamountofpayment { get; set; }
        public Nullable<decimal> Financialcost { get; set; }
        public Nullable<decimal> Totaltaxcost { get; set; }
        public Nullable<decimal> shuidian { get; set; }
        public string wangming { get; set; }
        public Nullable<int> Distinguish { get; set; }
        public string Costcategory { get; set; }
        public string purpose { get; set; }
        public Nullable<int> paystate { get; set; }
        public Nullable<int> readState { get; set; }
        public string pingtai { get; set; }
        public string Applicant { get; set; }
    }
}
